version: '3.8'

services:
  app:
    build: .
    container_name: web_react_vite_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
